#========================================
# Test profile settings (IT tests)
#========================================
integration:
  messaging:
    url: http://localhost:${wiremock.server.port:}/api-messaging
  pob:
    url: http://localhost:${wiremock.server.port:}/api-pob
    pobKey: some-key
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          messaging:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
