#========================================
# Test profile settings (IT tests)
#========================================
application:
  synchronization:
    tempFolder: ${project.build.directory}/tmp

integration:
  messaging:
    url: http://localhost:${wiremock.server.port:}/messaging
    channel: the-channel
    token: the-token
  pob:
    url: http://localhost:${wiremock.server.port:}/pob
    apiKey: some-key
  jira:
    password: some-password
    username: some-username
    url: http://localhost:${wiremock.server.port:}/jira
    projectKey: UF
spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          messaging:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
            
#========================================
# Scheduler settings
#
# - To disable the scheduling, set spring cron expression to "-" or remove "cronExpression"-property.
#========================================
scheduler:
  synchronizer:
    cron: "0/3 * * * * *"
  dbcleaner:
    cron: "-"