#========================================
# General settings
#========================================
application:
  # Synchronization-settings (between Jira, (this) microservice and POB).
  synchronization:
    # Clock-skew in seconds between microservice, pob and jira.
    clockSkewInSeconds: 15
    # The folder where files are temorarily stored during execution ("/temp" is a volume mount in openshift)
    tempFolder: /temp
    # The user group that is assigned POB-issues when Jira-ticket is closed.
    responsibleUserGroupInPob: IT-Support

logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  cache:
    cache-names: issueTypes
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=86400s
  application:
    name: api-incident-mapper
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: dbconnection-pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
integration:
  messaging:
    connectTimeout: 5
    readTimeout: 30
  pob:
    connect-timeout: 5
    read-timeout: 30
  jira:

#========================================
# Scheduler settings
#
# - To disable the scheduling, set spring cron expression to "-" or remove "cronExpression"-property.
#========================================
scheduler:
  synchronizer:
    # Every minute
    cron: "0 * * * * *"
    shedlock-lock-at-most-for: PT10M
  dbcleaner:
    # Every midnight
    cron: "0 0 0 * * *"
    shedlock-lock-at-most-for: PT10M
