#========================================
# Test profile settings (junit tests)
#========================================
application:
  synchronization:
    tempFolder: ${project.build.directory}
    
integration:
  messaging:
    url: http://messaging.url
  pob:
    url: http://pob.url
    apiKey: some-key
  jira:
    password: some-password
    username: some-username
    url: http://jira.url
    projectKey: PROJECT-KEY
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
        column_ordering_strategy: legacy
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          messaging:
            token-uri: http://token.url
        registration:
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
            
#========================================
# Scheduler settings
#
# - To disable the scheduling, set spring cron expression to "-" or remove "cronExpression"-property.
#========================================
scheduler:
  synchronizer:
    cron: "-"
  dbcleaner:
    cron: "-"
    