#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-incident-mapper
  security:
    oauth2:
      client:
        registration:
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
integration:
  messaging:
    connectTimeout: 5
    readTimeout: 30
  pob:
    connect-timeout: 5
    read-timeout: 30
