#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-incident-mapper
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: dbconnection-pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
integration:
  messaging:
    connectTimeout: 5
    readTimeout: 30
